### ISSUE TITLE
Not working with NW.js v0.13

### ISSUE THREAD

**Issue by citycide** [Spiffyk/twitch-node-sdk#7]
A detail - I'm using nw.js to run an express server that then runs the rest of my app. If I use `Twitch.init` by itself & only passing a client ID, I get console output that it connected. 

When I try to pass nw.gui to it, this is where I run into issues.

``` javascript
var gui = require('nw.gui');
Twitch.init({
      clientId: '<CLIENTID>',
      session: status,
      nw: gui
    }, function(error, status) {
      if (error) {
          console.log(error);
      }
      if (status.authenticated) {
          console.log('SYS: User is authenticated. ' + status);
      }
});
```

This results in `Uncaught Error: Invalid value for argument 2. Property 'toolbar': Unexpected property.`

I tried removing the `toolbar` property from twitch-sdk/twitch.js entirely. It passes this part now, obviously because we're just skipping the problem. But then it fails on `win.on('loaded'...` saying `on` is an unknown property of `win`. 

So... basically nw.gui is not being passed correctly to twitch-sdk. What's at fault here?

**Comment by Spiffyk** [comment]
It looks like the NWjs API (especially `Window`) has changed a lot between versions 0.12 and 0.13, rendering the twitch-sdk incompatible with it. I'll have to look into it in detail to fix it.

**Comment by Spiffyk** [comment]
I just checked if NW.js 0.12.3 is working and it seems to be. 0.12.3 is the current stable version of NW.js so please stick to that one for now if that is possible for you.

Also, I can't seem to get the DevTools in NW.js 0.13 to work so I can't fix things until I get that sorted.

**Comment by citycide** [comment]
Ah, you're right I had forgotten to mention I was using 0.13.

As for the DevTools, there's no toolbar anymore in 0.13. To access them you can right click the page and choose inspect / inspect background page. Background in my case is my backend / server.

**Comment by Spiffyk** [comment]
So, I have hopefully made the changes necessary to support NW.js 0.13 and pushed them to the repo. It still does not work, though, due to a bug in NW where the `loaded` event of a Window does not fire and I have no way around that so we need to wait for the NW devs to fix that.

The syntax for NW.js 0.13 will be different from 0.12 because we don't need to pass the `nw` object to the SDK anymore. It also makes a convenient way of keeping the SDK compatible with the older NW.js versions.

```javascript
Twitch.init({
      clientId: '<CLIENTID>',
      session: status,
      nw: true // we don't pass the nw object here, thus we have similar behaviour to electron
    }, function(error, status) {
      if (error) {
          console.log(error);
      }
      if (status.authenticated) {
          console.log('SYS: User is authenticated. ' + status);
      }
});
```

I'll leave this issue open until I know for sure that it really works.

PS: the problem with DevTools was that I had the NORMAL flavor of NW.js while I was supposed to use the SDK one. Silly me :smiley:

**Comment by Spiffyk** [comment]
Just updated the title to make the problem more clear.

**Comment by citycide** [comment]
Nicely done, NW has been quick to solve a lot of these issues from what I see so I'd think you'll be off & running soon enough. Thanks and I'll keep an eye out for 0.4.
